name: Publish

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirm to proceed with the publish action (type "yes" to confirm)'
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm install

    - name: Install 7-Zip and unzip/zip
      if: matrix.os == 'windows-latest'
      run: |
        choco install 7zip -y
        choco install unzip -y
        choco install zip -yy
    
    - name: Run tests
      run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
